waypoints:
  - id: 1
    position:
      x: 23.546051
      y: 3.093035
    euler_angle:
      z: -0.004294001990108822
  - id: 2
    position:
      x: 62.904152
      y: -9.027080
    euler_angle:
      z: -0.9580468181087708
  - id: 3
    position:
      x: 80.481033
      y: -15.560216
    euler_angle:
      z: 0.04512584984529758
  - id: 4
    position:
      x: 88.454605
      y: -19.325611
    euler_angle:
      z: 1.27833379038323
  - id: 5
    position:
      x: 88.766212
      y: 5.909473
    euler_angle:
      z: 3.130364591899961
    properties:
      - function: clear_costmap
  - id: 6
    position:
      x: 60.450546
      y: -9.364345
    euler_angle:
      z: -3.094128179068484
  - id: 7
    position:
      x: 35.174259
      y: -11.112434
    euler_angle:
      z: -2.211046191283573
  - id: 8
    position:
      x: 33.870193
      y: -18.362545
    euler_angle:
      z: 3.12159232026646
  - id: 9
    position:
      x: 6.977058
      y: -17.245096
    euler_angle:
      z: -2.986001686805593
  - id: 10
    position:
      x: 2.964502
      y: -24.698593
    euler_angle:
      z: -3.135956645964536
  - id: 11
    position:
      x: -23.767729
      y: -25.194139
    euler_angle:
      z: -3.131298610669695
    properties:
      - function: stop
  - id: 12
    position:
      x: -44.786896
      y: -33.015598
    euler_angle:
      z: 3.135876646288887
  - id: 13
    position:
      x: -59.262520
      y: -35.623474
    euler_angle:
      z: 3.135676647180349
    properties:
      - function: stop
  - id: 14
    position:
      x: -136.439514
      y: -39.813068
    euler_angle:
      z: -3.140320653761299
    properties:
      - function: stop
  - id: 15
    position:
      x: -228.966125
      y: -40.977612
    euler_angle:
      z: 2.123254468219335
  - id: 16
    position:
      x: -233.2303009033203
      y: 18.29995346069336
    euler_angle:
      z: 1.582036549224253
    properties:
      - function: stop_go
  - id: 17
    position:
      x: -234.952
      y: 42.047
    euler_angle:
      z: 1.595640445749372
    properties:
      - function: stop
      - function: waiting_line
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.2"
  - id: 18
    position:
      x: -236.303
      y: 44.119
    euler_angle:
      z: 2.299
    properties:
      - function: stop
      - function: param_change
        stop_after_and_keep: true
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_x
        param_value: "0.9"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_trans
        param_value: "0.9"
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.5"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/xy_goal_tolerance
        param_value: "1.0"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/yaw_goal_tolerance
        param_value: "0.8"
  - id: 19
    position:
      x: -255.45323181152344
      y: 42.4299430847168
    euler_angle:
      z: -0.91404
    properties:
      - function: stop_go
  - id: 20
    position:
      x: -252.908600
      y: 32.108791
    euler_angle:
      z: -3.124212430644687
    properties:
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_x
        param_value: "0.6"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_trans
        param_value: "0.6"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/xy_goal_tolerance
        param_value: "0.3"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/yaw_goal_tolerance
        param_value: "0.17"
      - function: obstacle_layer_controlle
        enable: true
  - id: 21
    position:
      x: -385.231781
      y: 23.704357
    euler_angle:
      z: -3.12421043071974
    properties:
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.05"
  - id: 22
    position:
      x: -527.134766
      y: 14.466932
    euler_angle:
      z: 1.942178013562939
    properties:
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.5"
  - id: 23
    position:
      x: -528.674316
      y: 40.434784
    euler_angle:
      z: 0.04147297245961398
  - id: 24
    position:
      x: -378.573
      y: 50.169
    euler_angle:
      z: 1.621422111596859
    properties:
      - function: stop
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.2"
  - id: 25
    position:
      x: -378.509613
      y: 67.508179
    euler_angle:
      z: 1.614631968107936
    properties:
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.5"
  - id: 26
    position:
      x: -380.796600
      y: 131.166107
    euler_angle:
      z: 2.3109672172004
  - id: 27
    position:
      x: -437.011475
      y: 134.384155
    euler_angle:
      z: 1.113368220887303
  - id: 28
    position:
      x: -365.128021
      y: 203.256836
    euler_angle:
      z: 1.687521033392737
  - id: 29
    position:
      x: -384.604004
      y: 279.355652
    euler_angle:
      z: 1.424990473371643
  - id: 30
    position:
      x: -387.026306
      y: 287.192474
    euler_angle:
      z: 2.78095562893758
    properties:
      - function: stop_go
  - id: 31
    position:
      x: -393.507202
      y: 284.132385
    euler_angle:
      z: -1.983452355784624
  - id: 32
    position:
      x: -386.801453
      y: 277.813354
    euler_angle:
      z: -0.845199547341102
    properties:
      - function: clear_costmap
  - id: 33
    position:
      x: -365.246918
      y: 205.115997
    euler_angle:
      z: -1.639581689479845
  - id: 34
    position:
      x: -436.212219
      y: 136.159103
    euler_angle:
      z: -2.039035685153904
  - id: 35
    position:
      x: -382.129059
      y: 132.614441
    euler_angle:
      z: -0.8520910410806566
  - id: 36
    position:
      x: -377.593842
      y: 58.392014
    euler_angle:
      z: -1.511135934347316
    properties:
      - function: stop
  - id: 37
    position:
      x: -376.819763
      y: 47.834438
    euler_angle:
      z: -1.546826230435682
  - id: 38
    position:
      x: -266.108
      y: 53.746
    euler_angle:
      z: 0.02397057812987367
    properties:
      - function: stop_go
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.2"
  - id: 39
    position:
      x: -256.868
      y: 45.774
    euler_angle:
      z: 0.02396857827314057
    properties:
      - function: stop
      - function: waiting_line
      - function: param_change
        param_name: /emcl2_node/odom_fw_dev_per_fw
        param_value: "0.5"
  - id: 40
    position:
      x: -250.368
      y: 47.322
    euler_angle:
      z: 0.05253404301220438
    properties:
      - function: stop
      - function: param_change
        stop_after_and_keep: true
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_x
        param_value: "0.9"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_trans
        param_value: "0.9"
  - id: 41
    position:
      x: -234.267807
      y: 47.432869
    euler_angle:
      z: -0.91404
    properties:
      - function: stop_go
  - id: 42
    position:
      x: -233.009094
      y: 41.366478
    euler_angle:
      z: -1.546823402209754
    properties:
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_x
        param_value: "0.6"
      - function: param_change
        param_name: /move_base/DWAPlannerROS/max_vel_trans
        param_value: "0.6"
      - function: obstacle_layer_controlle
        enable: true
  - id: 43
    position:
      x: -230.121933
      y: -39.221653
    euler_angle:
      z: -1.063990443064607
  - id: 44
    position:
      x: -143.142273
      y: -40.000992
    euler_angle:
      z: 0.00720401206807227
    properties:
      - function: stop
  - id: 45
    position:
      x: -70.006279
      y: -36.592751
    euler_angle:
      z: -0.02602474327628795
    properties:
      - function: goal